### ISSUE TITLE
JSON storage

### ISSUE THREAD

**Issue by bubnenkoff** [PiotrekDlang/AirLock#2]
Hi! Big thanks for you project! I am looking for compact DB that can be easy embeded with D apps. But now I need to store JSON. Would it be possible to do with your DB when it would be ready. I also would need some simple query like rethinkdb.com would it possible with AirLock?

**Comment by PiotrekDlang** [comment]
Hi,

I see no problem in using JSON with the db. Just treat JSON object like any other object and there is no reason is shouldn't work, e.g. 
auto found = db.collection!JSONobject("Objects").filer!(obj => obj.identity.name.canFind("J") &&  obj.age > 20);

As for a query language there is no plan to introduce any particular one. I guess things available in std.algorithm should do. OTOH, it might be necessary to reimplement some functions (e.g. filter, sort) when indexes are introduced.
 
Does it answer your questions?
BTW. If there is something unclear in docs let me know. Please mind that it is early version though.

Piotrek

**Comment by bubnenkoff** [comment]
Yes, thanks!

**Comment by PiotrekDlang** [comment]
I assume no further actions for this ticket is needed, thus closing. Thx for feedback.
