### ISSUE TITLE
active politics against Christianity?

### ISSUE THREAD

**Issue by bubnenkoff** [PiotrekDlang/AirLock#4]
Sorry, but what do you mean by this "active politics against Christianity"? Is it's joke?

**Comment by PiotrekDlang** [comment]
Both Github and Atlassian openly supports LGBT movement, which is at open war with Christianity.

**Comment by bubnenkoff** [comment]
Forgive my curiosity, but are you theist or just think that it's not normal? Just interesting. I dislike propaganda of them too.

**Comment by PiotrekDlang** [comment]
I'm just a catholic. However I also have atheist friends who don't agree with a propaganda of degenerating behaviour and LGBT movement does nasty things in Europe. 
I have respect for all people (sick or not), including homosexuals. But respect doesn’t indicate allowance for doing bad things (like forcing children to live with homo couples).

**Comment by PiotrekDlang** [comment]
Closing this hoping all is clear
