### ISSUE TITLE
Current status

### ISSUE THREAD

**Issue by bubnenkoff** [PiotrekDlang/AirLock#5]
I am needing small compact native D DB for storing JSON collections. Is there any chance that AirLock in nearest time will be suitable for it?

**Comment by PiotrekDlang** [comment]
Hi,

Thanks for your attention. The answer to your question depends on what reliability/performance you expect from this DB. 

FYI, I also plan to use this DB in "production", however this is a side project and I have a regular full time job. This means my resources I can put in the db development are limited. Nevertheless I am committed to this project and want to make it as much usable as I can.

My initial plan is to have basic reliable solution at version 0.2 (CRC for data, simple recovery and backup API, etc). 

I will upload a new roadmap today.

**Comment by bubnenkoff** [comment]
I need very low performance (for now). Only what I need good examples and easy to use API :)

**Comment by PiotrekDlang** [comment]
The v0.1 will be released in a week. I have to remove remaining, the most annoying shortcomings.

**Comment by bubnenkoff** [comment]
@PiotrekDlang maybe it would be handful for project https://github.com/putao-dev/flatbuffers

**Comment by PiotrekDlang** [comment]
> @PiotrekDlang maybe it would be handful for project https://github.com/putao-dev/flatbuffers
Can you elaborate? Isn't the flatbuffers a message passing project?

Anyway. I'm almost ready for releasing v0.1. Gitlab link will be provided soon.
If you see any obstacle with the latest commit please share your thoughts.

**Comment by bubnenkoff** [comment]
Big thanks! I will try it!

**Comment by bubnenkoff** [comment]
I can't build it:
`source\draft\database\storage.d(250,34): Error: cannot implicitly convert expression (cast(ulong)offset + count) of type ulong to uint
source\draft\database\storage.d(1236,35): Error: cannot implicitly convert expression (leftDataBytes <= cast(long)binSize ? leftDataBytes : cast(long)(binSize - 8u)) of type long to uint
source\draft\database\storage.d(1317,27): Error: cannot implicitly convert expression (bytesToRead) of type const(ulong) to uint
source\draft\database\storage.d(1355,42): Error: cannot implicitly convert expression (cast(ulong)dataOffset + dataLeft) of type ulong to uint
dmd failed with exit code 1.`

**Comment by PiotrekDlang** [comment]
This is because you are compiling on 32-bit OS, right? 
I have 64-bit OS so can't test it now.
However I plan to setup Gitlab CI soon to handle all configurations. 
For the time being I will check that on VM and will fix that today.

**Comment by bubnenkoff** [comment]
DMD on Windows even on x64 by default work in 32-bit mode (AFAIK).

**Comment by PiotrekDlang** [comment]
OK. DMD has -m32 switch witch I forgot about. After the latest commit the code should compile at least .

**Comment by PiotrekDlang** [comment]
This github repo is abandoned. The development is moved to https://gitlab.com/PiotrekDlang/DraftLib. I will leave this issue open for a few day and close it.
